const SEAT_DATA = {
  loc: '강남 BMT',
  theotor: '4관',
  date: '2023 / 01 / 01',
  runningTime: 120,
  seat: [
    { id: 1, status: 0 },
    { id: 2, status: 0 },
    { id: 3, status: 1 },
    { id: 4, status: 0 },
    { id: 5, status: 0 },
    { id: 6, status: 0 },
    { id: 7, status: 1 },
    { id: 8, status: 0 },
    { id: 9, status: 1 },
    { id: 10, status: 1 },
    { id: 11, status: 0 },
    { id: 12, status: 0 },
    { id: 13, status: 0 },
    { id: 14, status: 1 },
    { id: 15, status: 1 },
    { id: 16, status: 1 },
    { id: 17, status: 0 },
    { id: 18, status: 0 },
    { id: 19, status: 0 },
    { id: 20, status: 0 },
    { id: 21, status: 0 },
    { id: 22, status: 1 },
    { id: 23, status: 1 },
    { id: 24, status: 0 },
    { id: 25, status: 0 },
    { id: 26, status: 0 },
    { id: 27, status: 1 },
    { id: 28, status: 1 },
    { id: 29, status: 0 },
    { id: 30, status: 0 },
    { id: 31, status: 1 },
    { id: 32, status: 1 },
  ],
};

export default SEAT_DATA;
