// const SEAT_DATA = {
//   seat: [
//     { id: 1, seat_name: 'A1', status: 0 },
//     { id: 2, seat_name: 'A2', status: 0 },
//     { id: 3, seat_name: 'A3', status: 1 },
//     { id: 4, seat_name: 'A4', status: 0 },
//     { id: 5, seat_name: 'A5', status: 0 },
//     { id: 6, seat_name: 'A6', status: 0 },
//     { id: 7, seat_name: 'A7', status: 1 },
//     { id: 8, seat_name: 'A8', status: 0 },
//     { id: 9, seat_name: 'B1', status: 1 },
//     { id: 10, seat_name: 'B2', status: 1 },
//     { id: 11, seat_name: 'B3', status: 0 },
//     { id: 12, seat_name: 'B4', status: 0 },
//     { id: 13, seat_name: 'B5', status: 0 },
//     { id: 14, seat_name: 'B6', status: 1 },
//     { id: 15, seat_name: 'B7', status: 1 },
//     { id: 16, seat_name: 'B8', status: 1 },
//     { id: 17, seat_name: 'C1', status: 0 },
//     { id: 18, seat_name: 'C2', status: 0 },
//     { id: 19, seat_name: 'C3', status: 0 },
//     { id: 20, seat_name: 'C4', status: 0 },
//     { id: 21, seat_name: 'C5', status: 0 },
//     { id: 22, seat_name: 'C6', status: 1 },
//     { id: 23, seat_name: 'C7', status: 1 },
//     { id: 24, seat_name: 'C8', status: 0 },
//     { id: 25, seat_name: 'D1', status: 0 },
//     { id: 26, seat_name: 'D2', status: 0 },
//     { id: 27, seat_name: 'D3', status: 1 },
//     { id: 28, seat_name: 'D4', status: 1 },
//     { id: 29, seat_name: 'D5', status: 0 },
//     { id: 30, seat_name: 'D6', status: 0 },
//     { id: 31, seat_name: 'D7', status: 1 },
//     { id: 32, seat_name: 'D8', status: 1 },
//   ],
// };

const SEAT_DATA = {
  seat: [
    { id: 1, seat_name: 'A1' },
    { id: 2, seat_name: 'A2' },
    { id: 3, seat_name: 'A3' },
    { id: 4, seat_name: 'A4' },
    { id: 5, seat_name: 'A5' },
    { id: 6, seat_name: 'A6' },
    { id: 7, seat_name: 'A7' },
    { id: 8, seat_name: 'A8' },
    { id: 9, seat_name: 'B1' },
    { id: 10, seat_name: 'B2' },
    { id: 11, seat_name: 'B3' },
    { id: 12, seat_name: 'B4' },
    { id: 13, seat_name: 'B5' },
    { id: 14, seat_name: 'B6' },
    { id: 15, seat_name: 'B7' },
    { id: 16, seat_name: 'B8' },
    { id: 17, seat_name: 'C1' },
    { id: 18, seat_name: 'C2' },
    { id: 19, seat_name: 'C3' },
    { id: 20, seat_name: 'C4' },
    { id: 21, seat_name: 'C5' },
    { id: 22, seat_name: 'C6' },
    { id: 23, seat_name: 'C7' },
    { id: 24, seat_name: 'C8' },
    { id: 25, seat_name: 'D1' },
    { id: 26, seat_name: 'D2' },
    { id: 27, seat_name: 'D3' },
    { id: 28, seat_name: 'D4' },
    { id: 29, seat_name: 'D5' },
    { id: 30, seat_name: 'D6' },
    { id: 31, seat_name: 'D7' },
    { id: 32, seat_name: 'D8' },
  ],
};

export default SEAT_DATA;
